### ISSUE TITLE
Readme parameters wrong?

### ISSUE THREAD

**Issue by andrewtrotman** [jermp/interpolative_coding#1]
Hi,

In the readme it states

$ ./check leftmost_minimal ../data/test_collection.docs test.bin

but I think the parameters are the wrong way around, and it should be

$ ./check leftmost_minimal test.bin ../data/test_collection.docs

Thanks.

**Comment by jermp** [comment]
Hey hi,
I do not know really why I did not see this message until now!
Sorry for the late reply.
Anyway, yes: the parameters should be swapped and I corrected the readme.
Thanks!
